# Generated by Django 4.1.7 on 2023-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MC', 'Mobile Case'), ('SP', 'Screen Protector'), ('AC', 'Accessories')], max_length=50)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
