# Generated by Django 4.2.1 on 2023-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
