# Generated by Django 4.2.2 on 2023-06-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_customer_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razerpay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razerpay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razerpay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
